update=3/30/2015 9:27:20 PM
last_client=kicad
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=panel-cache
LibName2=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName3=C:/Program Files/KiCad/share/kicad/library/74xx
LibName4=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName5=C:/Program Files/KiCad/share/kicad/library/actel
LibName6=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName7=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName8=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName9=C:/Program Files/KiCad/share/kicad/library/atmel
LibName10=C:/Program Files/KiCad/share/kicad/library/audio
LibName11=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName12=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName13=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName14=C:/Program Files/KiCad/share/kicad/library/conn
LibName15=C:/Program Files/KiCad/share/kicad/library/contrib
LibName16=C:/Program Files/KiCad/share/kicad/library/cypress
LibName17=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName18=C:/Program Files/KiCad/share/kicad/library/device
LibName19=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName20=C:/Program Files/KiCad/share/kicad/library/display
LibName21=C:/Program Files/KiCad/share/kicad/library/dsp
LibName22=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName23=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName24=C:/Program Files/KiCad/share/kicad/library/gennum
LibName25=C:/Program Files/KiCad/share/kicad/library/graphic
LibName26=C:/Program Files/KiCad/share/kicad/library/hc11
LibName27=C:/Program Files/KiCad/share/kicad/library/intel
LibName28=C:/Program Files/KiCad/share/kicad/library/interface
LibName29=C:/Program Files/KiCad/share/kicad/library/ir
LibName30=C:/Program Files/KiCad/share/kicad/library/linear
LibName31=C:/Program Files/KiCad/share/kicad/library/logo
LibName32=C:/Program Files/KiCad/share/kicad/library/memory
LibName33=C:/Program Files/KiCad/share/kicad/library/microchip
LibName34=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName35=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName36=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName37=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName38=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName39=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName40=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName41=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName42=C:/Program Files/KiCad/share/kicad/library/motorola
LibName43=C:/Program Files/KiCad/share/kicad/library/msp430
LibName44=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName45=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName46=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName47=C:/Program Files/KiCad/share/kicad/library/opto
LibName48=C:/Program Files/KiCad/share/kicad/library/philips
LibName49=C:/Program Files/KiCad/share/kicad/library/power
LibName50=C:/Program Files/KiCad/share/kicad/library/powerint
LibName51=C:/Program Files/KiCad/share/kicad/library/pspice
LibName52=C:/Program Files/KiCad/share/kicad/library/references
LibName53=C:/Program Files/KiCad/share/kicad/library/regul
LibName54=C:/Program Files/KiCad/share/kicad/library/relays
LibName55=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName56=C:/Program Files/KiCad/share/kicad/library/sensors
LibName57=C:/Program Files/KiCad/share/kicad/library/silabs
LibName58=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName59=C:/Program Files/KiCad/share/kicad/library/special
LibName60=C:/Program Files/KiCad/share/kicad/library/stm8
LibName61=C:/Program Files/KiCad/share/kicad/library/stm32
LibName62=C:/Program Files/KiCad/share/kicad/library/supertex
LibName63=C:/Program Files/KiCad/share/kicad/library/switches
LibName64=C:/Program Files/KiCad/share/kicad/library/texas
LibName65=C:/Program Files/KiCad/share/kicad/library/transf
LibName66=C:/Program Files/KiCad/share/kicad/library/transistors
LibName67=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName68=C:/Program Files/KiCad/share/kicad/library/valves
LibName69=C:/Program Files/KiCad/share/kicad/library/video
LibName70=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName71=panel
LibName72=opendous/library/opendous
