ARDUINO_DIR = /usr/share/arduino
BOARD_TAG = uno
MONITOR_PORT = /dev/ttyACM0
ARDUINO_PORT = /dev/ttyACM0
OPTIMIZATION_LEVEL=3
#AVR_TOOLS_DIR = /usr
CFLAGS=-O3 -DMEMORY_SIZE=20
CPPFLAGS=-O3 -DMEMORY_SIZE=20
include /usr/share/arduino/Arduino.mk
